export enum SectionPage {
  HOME = 'home',
  NEWS = 'news',
  PRODUCT = 'product',
  PRODUCT_DETAIL = 'product_detail',
}

export enum SectionType {
  HERO_SLIDER = 'hero_slider',
  FEATURED_PRODUCTS = 'featured_products',
  PRODUCTS_BY_CATEGORY = 'products_by_category',
  NEWS = 'news',
  CUSTOM_HTML = 'custom_html',
  BANNER = 'banner',
  SIDE_BANNERS = 'side_banners',
  TESTIMONIALS = 'testimonials',
  CTA = 'cta',
  FEATURES = 'features',
  GALLERY = 'gallery',
  TEAM = 'team',
  CONTACT_FORM = 'contact_form',
  VIDEO = 'video',
  STATS = 'stats',
  BRAND_SHOWCASE = 'brand_showcase',
  WHY_CHOOSE_US = 'why_choose_us',
}

export const SECTION_TYPE_LABELS: Record<SectionType, string> = {
  [SectionType.HERO_SLIDER]: 'Hero Slider',
  [SectionType.FEATURED_PRODUCTS]: 'Featured Products',
  [SectionType.PRODUCTS_BY_CATEGORY]: 'Products by Category',
  [SectionType.NEWS]: 'News',
  [SectionType.CUSTOM_HTML]: 'Custom HTML',
  [SectionType.BANNER]: 'Banner',
  [SectionType.SIDE_BANNERS]: 'Dual Side Banners',
  [SectionType.TESTIMONIALS]: 'Testimonials',
  [SectionType.CTA]: 'Call to Action',
  [SectionType.FEATURES]: 'Features/Services',
  [SectionType.GALLERY]: 'Gallery',
  [SectionType.TEAM]: 'Team',
  [SectionType.CONTACT_FORM]: 'Contact Form',
  [SectionType.VIDEO]: 'Video',
  [SectionType.STATS]: 'Statistics',
  [SectionType.BRAND_SHOWCASE]: 'Brand showcase',
  [SectionType.WHY_CHOOSE_US]: 'Why choose us',
};
