// AppRouter types for tRPC client
// This file is auto-generated from actual nestjs-trpc routers
// Run 'npm run sync:trpc-types' to regenerate this file
// Generated on: 2025-10-17T17:29:38.890Z

import { initTRPC } from '@trpc/server';
import { z } from 'zod';

// Initialize tRPC for type creation
const t = initTRPC.create();

// Define the AppRouter using tRPC's router structure
// This matches the actual @Router aliases and procedures from nestjs-trpc routers
const appRouter = t.router({
  adminChartData: t.router({
    getChartData: t.procedure.input(z.any().optional()).query(() => null),
    getAvailableChartTypes: t.procedure.input(z.any().optional()).query(() => null),
  }),
  adminEmailChannel: t.router({
    createChannel: t.procedure.input(z.any()).mutation(() => null),
    getChannels: t.procedure.input(z.any().optional()).query(() => null),
    getChannelById: t.procedure.input(z.any().optional()).query(() => null),
    getActiveChannels: t.procedure.input(z.any().optional()).query(() => null),
    getChannelsByUsageType: t.procedure.input(z.any().optional()).query(() => null),
    getDefaultChannel: t.procedure.input(z.any().optional()).query(() => null),
    updateChannel: t.procedure.input(z.any()).mutation(() => null),
    deleteChannel: t.procedure.input(z.any()).mutation(() => null),
    setAsDefault: t.procedure.input(z.any()).mutation(() => null),
    testChannel: t.procedure.input(z.any()).mutation(() => null),
    cloneChannel: t.procedure.input(z.any()).mutation(() => null),
  }),
  adminFirebaseConfig: t.router({
    getAllConfigs: t.procedure.input(z.any().optional()).query(() => null),
    getConfig: t.procedure.input(z.any().optional()).query(() => null),
    createConfig: t.procedure.input(z.any()).mutation(() => null),
    updateConfig: t.procedure.input(z.any()).mutation(() => null),
    deleteConfig: t.procedure.input(z.any()).mutation(() => null),
  }),
  adminLanguage: t.router({
    getLanguages: t.procedure.input(z.any().optional()).query(() => null),
    getActiveLanguages: t.procedure.input(z.any().optional()).query(() => null),
    getLanguageById: t.procedure.input(z.any().optional()).query(() => null),
    getDefaultLanguage: t.procedure.input(z.any().optional()).query(() => null),
    createLanguage: t.procedure.input(z.any()).mutation(() => null),
    updateLanguage: t.procedure.input(z.any()).mutation(() => null),
    deleteLanguage: t.procedure.input(z.any()).mutation(() => null),
    setDefaultLanguage: t.procedure.input(z.any()).mutation(() => null),
    toggleLanguageStatus: t.procedure.input(z.any()).mutation(() => null),
    updateSortOrders: t.procedure.input(z.any()).mutation(() => null),
  }),
  clientLanguage: t.router({
    getActiveLanguages: t.procedure.input(z.any().optional()).query(() => null),
    getDefaultLanguage: t.procedure.input(z.any().optional()).query(() => null),
  }),
  adminMailTemplate: t.router({
    createTemplate: t.procedure.input(z.any()).mutation(() => null),
    getTemplates: t.procedure.input(z.any().optional()).query(() => null),
    getTemplateById: t.procedure.input(z.any().optional()).query(() => null),
    getTemplateByName: t.procedure.input(z.any().optional()).query(() => null),
    updateTemplate: t.procedure.input(z.any()).mutation(() => null),
    deleteTemplate: t.procedure.input(z.any()).mutation(() => null),
    processTemplate: t.procedure.input(z.any()).mutation(() => null),
    cloneTemplate: t.procedure.input(z.any()).mutation(() => null),
    getTemplateTypes: t.procedure.input(z.any().optional()).query(() => null),
    getStatistics: t.procedure.input(z.any().optional()).query(() => null),
    bulkUpdateStatus: t.procedure.input(z.any()).mutation(() => null),
    searchTemplates: t.procedure.input(z.any().optional()).query(() => null),
  }),
  adminMenus: t.router({
    list: t.procedure.input(z.any()).query(() => null),
    byId: t.procedure.input(z.any().optional()).query(() => null),
    tree: t.procedure.input(z.any().optional()).query(() => null),
    groups: t.procedure.input(z.any().optional()).query(() => null),
    create: t.procedure.input(z.any()).mutation(() => null),
    update: t.procedure.input(z.any()).mutation(() => null),
    delete: t.procedure.input(z.any()).mutation(() => null),
    reorder: t.procedure.input(z.any()).mutation(() => null),
  }),
  adminNotificationPreferences: t.router({
    getUserPreferences: t.procedure.input(z.any().optional()).query(() => null),
    getUserPreferencesRaw: t.procedure.input(z.any().optional()).query(() => null),
    createPreference: t.procedure.input(z.any()).mutation(() => null),
    updatePreference: t.procedure.input(z.any()).mutation(() => null),
    updateUserPreference: t.procedure.input(z.any()).mutation(() => null),
    bulkUpdateUserPreferences: t.procedure.input(z.any()).mutation(() => null),
    deletePreference: t.procedure.input(z.any()).mutation(() => null),
    initializeUserPreferences: t.procedure.input(z.any()).mutation(() => null),
    toggleNotificationType: t.procedure.input(z.any()).mutation(() => null),
    setQuietHours: t.procedure.input(z.any()).mutation(() => null),
    getQuietHours: t.procedure.input(z.any().optional()).query(() => null),
    canSendNotification: t.procedure.input(z.any().optional()).query(() => null),
  }),
  adminNotification: t.router({
    getNotifications: t.procedure.input(z.any().optional()).query(() => null),
    getUserNotifications: t.procedure.input(z.any().optional()).query(() => null),
    getNotificationById: t.procedure.input(z.any().optional()).query(() => null),
    getUnreadCount: t.procedure.input(z.any().optional()).query(() => null),
    getRecentNotifications: t.procedure.input(z.any().optional()).query(() => null),
    getNotificationStats: t.procedure.input(z.any().optional()).query(() => null),
    createNotification: t.procedure.input(z.any()).mutation(() => null),
    debugSendNotification: t.procedure.input(z.any()).mutation(() => null),
    sendNotificationToUser: t.procedure.input(z.any()).mutation(() => null),
    sendBulkNotifications: t.procedure.input(z.any()).mutation(() => null),
    sendTopicNotification: t.procedure.input(z.any()).mutation(() => null),
    markAsRead: t.procedure.input(z.any()).mutation(() => null),
    markAllAsRead: t.procedure.input(z.any()).mutation(() => null),
    deleteNotification: t.procedure.input(z.any()).mutation(() => null),
    deleteUserNotifications: t.procedure.input(z.any()).mutation(() => null),
    subscribeToTopic: t.procedure.input(z.any()).mutation(() => null),
    unsubscribeFromTopic: t.procedure.input(z.any()).mutation(() => null),
    validateFCMToken: t.procedure.input(z.any()).mutation(() => null),
    sendTestNotification: t.procedure.input(z.any()).mutation(() => null),
    cleanupNotifications: t.procedure.input(z.any()).mutation(() => null),
  }),
  clientNotification: t.router({
    getUserNotifications: t.procedure.input(z.any().optional()).query(() => null),
    getUnreadCount: t.procedure.input(z.any().optional()).query(() => null),
    getRecentNotifications: t.procedure.input(z.any().optional()).query(() => null),
    createNotification: t.procedure.input(z.any()).mutation(() => null),
    markAllAsRead: t.procedure.input(z.any()).mutation(() => null),
    validateFCMToken: t.procedure.input(z.any()).mutation(() => null),
    subscribeToTopic: t.procedure.input(z.any()).mutation(() => null),
    unsubscribeFromTopic: t.procedure.input(z.any()).mutation(() => null),
    getNotificationTypes: t.procedure.input(z.any().optional()).query(() => null),
  }),
  userNotification: t.router({
    getMyNotifications: t.procedure.input(z.any().optional()).query(() => null),
    getMyRecentNotifications: t.procedure.input(z.any().optional()).query(() => null),
    getMyUnreadCount: t.procedure.input(z.any().optional()).query(() => null),
    getMyNotificationById: t.procedure.input(z.any().optional()).query(() => null),
    getMyNotificationStats: t.procedure.input(z.any().optional()).query(() => null),
    markMyNotificationAsRead: t.procedure.input(z.any()).mutation(() => null),
    markMultipleAsRead: t.procedure.input(z.any()).mutation(() => null),
    markAllMyNotificationsAsRead: t.procedure.input(z.any()).mutation(() => null),
    deleteMyNotification: t.procedure.input(z.any()).mutation(() => null),
    deleteMyOldNotifications: t.procedure.input(z.any()).mutation(() => null),
    registerFCMToken: t.procedure.input(z.any()).mutation(() => null),
    testMyNotification: t.procedure.input(z.any()).mutation(() => null),
  }),
  adminPostCategories: t.router({
    getCategories: t.procedure.input(z.any().optional()).query(() => null),
    getCategoryById: t.procedure.input(z.any().optional()).query(() => null),
    createCategory: t.procedure.input(z.any()).mutation(() => null),
    updateCategory: t.procedure.input(z.any()).mutation(() => null),
    deleteCategory: t.procedure.input(z.any()).mutation(() => null),
  }),
  adminPostTags: t.router({
    getTags: t.procedure.input(z.any().optional()).query(() => null),
    searchTags: t.procedure.input(z.any().optional()).query(() => null),
    getTagById: t.procedure.input(z.any().optional()).query(() => null),
    createTag: t.procedure.input(z.any()).mutation(() => null),
    updateTag: t.procedure.input(z.any()).mutation(() => null),
    deleteTag: t.procedure.input(z.any()).mutation(() => null),
    getPopularTags: t.procedure.input(z.any().optional()).query(() => null),
  }),
  adminPosts: t.router({
    getPosts: t.procedure.input(z.any().optional()).query(() => null),
    getPostById: t.procedure.input(z.any().optional()).query(() => null),
  }),
  adminProductAttributes: t.router({
    getAll: t.procedure.input(z.any().optional()).query(() => null),
    getById: t.procedure.input(z.any()).query(() => null),
    getSelectAttributes: t.procedure.input(z.any().optional()).query(() => null),
    getFilterableAttributes: t.procedure.input(z.any().optional()).query(() => null),
    create: t.procedure.input(z.any()).mutation(() => null),
    update: t.procedure.input(z.any()).mutation(() => null),
    delete: t.procedure.input(z.any()).mutation(() => null),
    getAttributeValues: t.procedure.input(z.any().optional()).query(() => null),
    createAttributeValue: t.procedure.input(z.any()).mutation(() => null),
    updateAttributeValue: t.procedure.input(z.any()).mutation(() => null),
    deleteAttributeValue: t.procedure.input(z.any()).mutation(() => null),
    getStats: t.procedure.input(z.any().optional()).query(() => null),
    getAttributeTranslations: t.procedure.input(z.any()).query(() => null),
    getByIdWithTranslations: t.procedure.input(z.any()).query(() => null),
    createAttributeTranslation: t.procedure.input(z.any()).mutation(() => null),
    updateAttributeTranslation: t.procedure.input(z.any()).mutation(() => null),
    deleteAttributeTranslation: t.procedure.input(z.any()).mutation(() => null),
  }),
  adminProductBrands: t.router({
    getAll: t.procedure.input(z.any().optional()).query(() => null),
    getById: t.procedure.input(z.any()).query(() => null),
    create: t.procedure.input(z.any()).mutation(() => null),
    update: t.procedure.input(z.any()).mutation(() => null),
    delete: t.procedure.input(z.any()).mutation(() => null),
    getStats: t.procedure.input(z.any().optional()).query(() => null),
    getBrandTranslations: t.procedure.input(z.any()).query(() => null),
    getByIdWithTranslations: t.procedure.input(z.any()).query(() => null),
    createBrandTranslation: t.procedure.input(z.any()).mutation(() => null),
    updateBrandTranslation: t.procedure.input(z.any()).mutation(() => null),
    deleteBrandTranslation: t.procedure.input(z.any()).mutation(() => null),
  }),
  adminProductCategories: t.router({
    getAll: t.procedure.input(z.any().optional()).query(() => null),
    getTree: t.procedure.input(z.any().optional()).query(() => null),
    getRootCategories: t.procedure.input(z.any().optional()).query(() => null),
    getCategoryChildren: t.procedure.input(z.any().optional()).query(() => null),
    getFilteredTree: t.procedure.input(z.any().optional()).query(() => null),
    getById: t.procedure.input(z.any()).query(() => null),
    create: t.procedure.input(z.any()).mutation(() => null),
    update: t.procedure.input(z.any()).mutation(() => null),
    delete: t.procedure.input(z.any()).mutation(() => null),
    getStats: t.procedure.input(z.any().optional()).query(() => null),
    getCategoryTranslations: t.procedure.input(z.any()).query(() => null),
    getByIdWithTranslations: t.procedure.input(z.any()).query(() => null),
    getTreeWithTranslations: t.procedure.input(z.any().optional()).query(() => null),
    createCategoryTranslation: t.procedure.input(z.any()).mutation(() => null),
    updateCategoryTranslation: t.procedure.input(z.any()).mutation(() => null),
    deleteCategoryTranslation: t.procedure.input(z.any()).mutation(() => null),
  }),
  adminCustomers: t.router({
    list: t.procedure.input(z.any()).query(() => null),
    detail: t.procedure.input(z.any()).query(() => null),
    create: t.procedure.input(z.any()).mutation(() => null),
    update: t.procedure.input(z.any()).mutation(() => null),
    delete: t.procedure.input(z.any()).mutation(() => null),
    stats: t.procedure.input(z.any().optional()).query(() => null),
    updateStatus: t.procedure.input(z.any()).mutation(() => null),
    search: t.procedure.input(z.any().optional()).query(() => null),
    topCustomers: t.procedure.input(z.any().optional()).query(() => null),
    recentCustomers: t.procedure.input(z.any().optional()).query(() => null),
    inactiveCustomers: t.procedure.input(z.any().optional()).query(() => null),
    customersByTag: t.procedure.input(z.any().optional()).query(() => null),
    addLoyaltyPoints: t.procedure.input(z.any()).mutation(() => null),
    redeemLoyaltyPoints: t.procedure.input(z.any()).mutation(() => null),
    bulkUpdateStatus: t.procedure.input(z.any()).mutation(() => null),
  }),
  adminDeliveryMethods: t.router({
    list: t.procedure.input(z.any()).query(() => null),
    getById: t.procedure.input(z.any()).query(() => null),
    getActive: t.procedure.input(z.any().optional()).query(() => null),
    getByType: t.procedure.input(z.any().optional()).query(() => null),
    create: t.procedure.input(z.any()).mutation(() => null),
    update: t.procedure.input(z.any()).mutation(() => null),
    delete: t.procedure.input(z.any()).mutation(() => null),
    setDefault: t.procedure.input(z.any()).mutation(() => null),
    toggleActive: t.procedure.input(z.any()).mutation(() => null),
    reorder: t.procedure.input(z.any()).mutation(() => null),
    calculateDelivery: t.procedure.input(z.any().optional()).query(() => null),
    getQuotes: t.procedure.input(z.any().optional()).query(() => null),
    stats: t.procedure.input(z.any().optional()).query(() => null),
  }),
  adminOrders: t.router({
    list: t.procedure.input(z.any()).query(() => null),
    detail: t.procedure.input(z.any()).query(() => null),
    getByOrderNumber: t.procedure.input(z.any().optional()).query(() => null),
    create: t.procedure.input(z.any()).mutation(() => null),
    update: t.procedure.input(z.any()).mutation(() => null),
    updateStatus: t.procedure.input(z.any()).mutation(() => null),
    updatePaymentStatus: t.procedure.input(z.any()).mutation(() => null),
    cancel: t.procedure.input(z.any()).mutation(() => null),
    refund: t.procedure.input(z.any()).mutation(() => null),
    ship: t.procedure.input(z.any()).mutation(() => null),
    fulfill: t.procedure.input(z.any()).mutation(() => null),
    delete: t.procedure.input(z.any()).mutation(() => null),
    stats: t.procedure.input(z.any().optional()).query(() => null),
    getByCustomer: t.procedure.input(z.any().optional()).query(() => null),
    getByCustomerEmail: t.procedure.input(z.any().optional()).query(() => null),
    getProductPrice: t.procedure.input(z.any().optional()).query(() => null),
    fulfillItem: t.procedure.input(z.any()).mutation(() => null),
    refundItem: t.procedure.input(z.any()).mutation(() => null),
    deleteItem: t.procedure.input(z.any()).mutation(() => null),
  }),
  adminPaymentMethods: t.router({
    list: t.procedure.input(z.any()).query(() => null),
    active: t.procedure.input(z.any().optional()).query(() => null),
    forAmount: t.procedure.input(z.any().optional()).query(() => null),
    getById: t.procedure.input(z.any()).query(() => null),
    create: t.procedure.input(z.any()).mutation(() => null),
    update: t.procedure.input(z.any()).mutation(() => null),
    delete: t.procedure.input(z.any()).mutation(() => null),
    setDefault: t.procedure.input(z.any()).mutation(() => null),
    toggleActive: t.procedure.input(z.any()).mutation(() => null),
    reorder: t.procedure.input(z.any()).mutation(() => null),
    calculatePayment: t.procedure.input(z.any().optional()).query(() => null),
    stats: t.procedure.input(z.any().optional()).query(() => null),
  }),
  adminPurchaseOrders: t.router({
    list: t.procedure.input(z.any()).query(() => null),
    create: t.procedure.input(z.any()).mutation(() => null),
    detail: t.procedure.input(z.any()).query(() => null),
    update: t.procedure.input(z.any()).mutation(() => null),
    delete: t.procedure.input(z.any()).mutation(() => null),
    approve: t.procedure.input(z.any()).mutation(() => null),
    send: t.procedure.input(z.any()).mutation(() => null),
    cancel: t.procedure.input(z.any()).mutation(() => null),
    receiveItems: t.procedure.input(z.any()).mutation(() => null),
    getOverdueOrders: t.procedure.input(z.any().optional()).query(() => null),
    getPendingReceivingOrders: t.procedure.input(z.any().optional()).query(() => null),
    getOrderStats: t.procedure.input(z.any().optional()).query(() => null),
  }),
  adminProductSuppliers: t.router({
    getAll: t.procedure.input(z.any().optional()).query(() => null),
    getById: t.procedure.input(z.any()).query(() => null),
    create: t.procedure.input(z.any()).mutation(() => null),
    update: t.procedure.input(z.any()).mutation(() => null),
    delete: t.procedure.input(z.any()).mutation(() => null),
    getStats: t.procedure.input(z.any().optional()).query(() => null),
    getSupplierTranslations: t.procedure.input(z.any().optional()).query(() => null),
    getByIdWithTranslations: t.procedure.input(z.any()).query(() => null),
    createSupplierTranslation: t.procedure.input(z.any()).mutation(() => null),
    updateSupplierTranslation: t.procedure.input(z.any()).mutation(() => null),
    deleteSupplierTranslation: t.procedure.input(z.any()).mutation(() => null),
  }),
  adminWarehouses: t.router({
    getAll: t.procedure.input(z.any().optional()).query(() => null),
    create: t.procedure.input(z.any()).mutation(() => null),
    getById: t.procedure.input(z.any()).query(() => null),
    update: t.procedure.input(z.any()).mutation(() => null),
    delete: t.procedure.input(z.any()).mutation(() => null),
    getStats: t.procedure.input(z.any().optional()).query(() => null),
    getInventory: t.procedure.input(z.any().optional()).query(() => null),
    adjustStock: t.procedure.input(z.any()).mutation(() => null),
    getMovements: t.procedure.input(z.any().optional()).query(() => null),
    getLowStock: t.procedure.input(z.any().optional()).query(() => null),
    getOutOfStock: t.procedure.input(z.any().optional()).query(() => null),
    getExpiringSoon: t.procedure.input(z.any().optional()).query(() => null),
  }),
  adminWishlist: t.router({
    list: t.procedure.input(z.any()).query(() => null),
    detail: t.procedure.input(z.any()).query(() => null),
    create: t.procedure.input(z.any()).mutation(() => null),
    update: t.procedure.input(z.any()).mutation(() => null),
    delete: t.procedure.input(z.any()).mutation(() => null),
    updatePriority: t.procedure.input(z.any()).mutation(() => null),
    stats: t.procedure.input(z.any().optional()).query(() => null),
  }),
  adminProducts: t.router({
    list: t.procedure.input(z.any()).query(() => null),
    addTestMedia: t.procedure.input(z.any()).mutation(() => null),
    detail: t.procedure.input(z.any()).query(() => null),
    variantDetail: t.procedure.input(z.any().optional()).query(() => null),
    create: t.procedure.input(z.any()).mutation(() => null),
    update: t.procedure.input(z.any()).mutation(() => null),
    updateVariant: t.procedure.input(z.any()).mutation(() => null),
    delete: t.procedure.input(z.any()).mutation(() => null),
    stats: t.procedure.input(z.any().optional()).query(() => null),
    updateStatus: t.procedure.input(z.any()).mutation(() => null),
  }),
  clientOrders: t.router({
    list: t.procedure.input(z.any()).query(() => null),
    detail: t.procedure.input(z.any()).query(() => null),
    recent: t.procedure.input(z.any().optional()).query(() => null),
    active: t.procedure.input(z.any().optional()).query(() => null),
    cancelOrder: t.procedure.input(z.any()).mutation(() => null),
  }),
  publicProducts: t.router({
    list: t.procedure.input(z.any()).query(() => null),
    detail: t.procedure.input(z.any()).query(() => null),
    featured: t.procedure.input(z.any().optional()).query(() => null),
    byCategory: t.procedure.input(z.any().optional()).query(() => null),
    byBrand: t.procedure.input(z.any().optional()).query(() => null),
    search: t.procedure.input(z.any().optional()).query(() => null),
  }),
  'admin.seo': t.router({
    getAll: t.procedure.input(z.any().optional()).query(() => null),
    getByPath: t.procedure.input(z.any()).query(() => null),
    create: t.procedure.input(z.any()).mutation(() => null),
    update: t.procedure.input(z.any()).mutation(() => null),
    delete: t.procedure.input(z.any()).mutation(() => null),
  }),
  'admin.settings': t.router({
    getAll: t.procedure.input(z.any().optional()).query(() => null),
    list: t.procedure.input(z.any()).query(() => null),
    getById: t.procedure.input(z.any()).query(() => null),
    getByKey: t.procedure.input(z.any().optional()).query(() => null),
    getByGroup: t.procedure.input(z.any().optional()).query(() => null),
    create: t.procedure.input(z.any()).mutation(() => null),
    update: t.procedure.input(z.any()).mutation(() => null),
    bulkUpdate: t.procedure.input(z.any()).mutation(() => null),
    delete: t.procedure.input(z.any()).mutation(() => null),
    updateVisibility: t.procedure.input(z.any()).mutation(() => null),
  }),
  adminMedia: t.router({
    getUserMedia: t.procedure
      .input(
        z
          .object({
            page: z.number().min(1).default(1),
            limit: z.number().min(1).max(100).default(20),
            type: z
              .enum(['audio', 'video', 'image', 'document', 'other'])
              .optional(),
            folder: z.string().optional(),
            search: z.string().optional(),
            sortBy: z
              .enum(['createdAt', 'updatedAt', 'filename', 'originalName', 'size'])
              .default('createdAt'),
            sortOrder: z.enum(['ASC', 'DESC']).default('DESC'),
          })
          .optional()
      )
      .query(() => null),
    getMediaById: t.procedure.input(z.any().optional()).query(() => null),
    updateMedia: t.procedure.input(z.any()).mutation(() => null),
    deleteMedia: t.procedure.input(z.any()).mutation(() => null),
    deleteMultipleMedia: t.procedure.input(z.any()).mutation(() => null),
    getMediaStats: t.procedure.input(z.any().optional()).query(() => null),
    getRecentMedia: t.procedure.input(z.any().optional()).query(() => null),
  }),
  adminStorage: t.router({
    getStorageConfig: t.procedure.input(z.any().optional()).query(() => null),
    updateStorageConfig: t.procedure.input(z.any()).mutation(() => null),
    testStorageConnection: t.procedure.input(z.any()).mutation(() => null),
  }),
  adminSupportClients: t.router({
    getAll: t.procedure.input(z.any().optional()).query(() => null),
    getById: t.procedure.input(z.any()).query(() => null),
    getDefault: t.procedure.input(z.any().optional()).query(() => null),
    create: t.procedure.input(z.any()).mutation(() => null),
    update: t.procedure.input(z.any()).mutation(() => null),
    delete: t.procedure.input(z.any()).mutation(() => null),
    setAsDefault: t.procedure.input(z.any()).mutation(() => null),
    updateSortOrder: t.procedure.input(z.any()).mutation(() => null),
    duplicate: t.procedure.input(z.any()).mutation(() => null),
    getWidgetScripts: t.procedure.input(z.any().optional()).query(() => null),
    getAvailableClients: t.procedure.input(z.any().optional()).query(() => null),
    getStats: t.procedure.input(z.any().optional()).query(() => null),
    validateConfiguration: t.procedure.input(z.any()).mutation(() => null),
    getRecommendedSettings: t.procedure.input(z.any().optional()).query(() => null),
    getTypes: t.procedure.input(z.any().optional()).query(() => null),
    getWidgetPositions: t.procedure.input(z.any().optional()).query(() => null),
    getWidgetThemes: t.procedure.input(z.any().optional()).query(() => null),
    testAvailability: t.procedure.input(z.any().optional()).query(() => null),
  }),
  adminAddressBook: t.router({
    list: t.procedure.input(z.any()).query(() => null),
    detail: t.procedure.input(z.any()).query(() => null),
    getByUserId: t.procedure
      .input(z.object({ userId: z.string().uuid() }))
      .query(() => null),
    getByUserIdAndType: t.procedure
      .input(
        z.object({
          userId: z.string().uuid(),
          addressType: z.enum(['BILLING', 'SHIPPING', 'BOTH']),
        })
      )
      .query(() => null),
    create: t.procedure.input(z.any()).mutation(() => null),
    update: t.procedure.input(z.any()).mutation(() => null),
    delete: t.procedure.input(z.any()).mutation(() => null),
    setAsDefault: t.procedure.input(z.any()).mutation(() => null),
    stats: t.procedure.input(z.any().optional()).query(() => null),
  }),
  adminPermission: t.router({
    createPermission: t.procedure.input(z.any()).mutation(() => null),
    getAllPermissions: t.procedure.input(z.any().optional()).query(() => null),
    getPermissionById: t.procedure.input(z.any().optional()).query(() => null),
    updatePermission: t.procedure.input(z.any()).mutation(() => null),
    deletePermission: t.procedure.input(z.any()).mutation(() => null),
    assignPermissionToRole: t.procedure.input(z.any()).mutation(() => null),
    removePermissionFromRole: t.procedure.input(z.any()).mutation(() => null),
    getRolePermissions: t.procedure.input(z.any().optional()).query(() => null),
    grantPermissions: t.procedure.input(z.any()).mutation(() => null),
    checkPermission: t.procedure.input(z.any().optional()).query(() => null),
  }),
  adminRole: t.router({
    getAllRoles: t.procedure
      .input(
        z.object({
          page: z.number().min(1).optional().default(1),
          limit: z.number().min(1).max(100).optional().default(10),
          search: z.string().optional(),
          isActive: z.boolean().optional(),
          isDefault: z.boolean().optional(),
        })
      )
      .query(() => null),
    getRoleById: t.procedure.input(z.any().optional()).query(() => null),
    createRole: t.procedure.input(z.any()).mutation(() => null),
    updateRole: t.procedure.input(z.any()).mutation(() => null),
    deleteRole: t.procedure.input(z.any()).mutation(() => null),
    getAvailablePermissions: t.procedure.input(z.any().optional()).query(() => null),
    getRoleStatistics: t.procedure.input(z.any().optional()).query(() => null),
    toggleRoleStatus: t.procedure.input(z.any()).mutation(() => null),
    duplicateRole: t.procedure.input(z.any()).mutation(() => null),
    addPermissionsToRole: t.procedure.input(z.any()).mutation(() => null),
    searchUsersForRole: t.procedure.input(z.any().optional()).query(() => null),
    addUsersToRole: t.procedure.input(z.any()).mutation(() => null),
  }),
  adminUserActivity: t.router({
    getUserActivityStatus: t.procedure.input(z.any().optional()).query(() => null),
    getBulkUserActivityStatus: t.procedure.input(z.any().optional()).query(() => null),
    getCurrentlyActiveUsers: t.procedure.input(z.any().optional()).query(() => null),
    getRecentlyActiveUsers: t.procedure.input(z.any().optional()).query(() => null),
    getActivitySummary: t.procedure.input(z.any().optional()).query(() => null),
  }),
  adminUserStatistics: t.router({
    getUserStatistics: t.procedure.input(z.any().optional()).query(() => null),
  }),
  adminUser: t.router({
    createUser: t.procedure.input(z.any()).mutation(() => null),
    getAllUsers: t.procedure.input(z.any().optional()).query(() => null),
    getUserById: t.procedure.input(z.any().optional()).query(() => null),
    updateUser: t.procedure.input(z.any()).mutation(() => null),
    deleteUser: t.procedure.input(z.any()).mutation(() => null),
    updateUserStatus: t.procedure.input(z.any()).mutation(() => null),
    updateUserProfileById: t.procedure.input(z.any()).mutation(() => null),
    getProfile: t.procedure.input(z.any().optional()).query(() => null),
    updateProfile: t.procedure.input(z.any()).mutation(() => null),
    updatePassword: t.procedure.input(z.any()).mutation(() => null),
  }),
  clientAddressBook: t.router({
    getAddresses: t.procedure.input(z.any().optional()).query(() => null),
    getAddressById: t.procedure.input(z.any()).query(() => null),
    createAddress: t.procedure.input(z.any()).mutation(() => null),
    updateAddress: t.procedure.input(z.any()).mutation(() => null),
    deleteAddress: t.procedure.input(z.any()).mutation(() => null),
    setDefaultAddress: t.procedure.input(z.any()).mutation(() => null),
    getDefaultAddress: t.procedure.input(z.any().optional()).query(() => null),
    getCountries: t.procedure.input(z.any().optional()).query(() => null),
    getAdministrativeDivisions: t.procedure.input(z.any()).query(() => null),
    getAdministrativeDivisionsByParentId: t.procedure.input(z.any()).query(() => null),
  }),
  clientSecurity: t.router({
    getSecurityStatus: t.procedure.input(z.any().optional()).query(() => null),
    changePassword: t.procedure.input(z.any()).mutation(() => null),
    setup2FA: t.procedure.input(z.any()).mutation(() => null),
    verify2FA: t.procedure.input(z.any()).mutation(() => null),
    disable2FA: t.procedure.input(z.any()).mutation(() => null),
    getActiveSessions: t.procedure.input(z.any().optional()).query(() => null),
    revokeSession: t.procedure.input(z.any()).mutation(() => null),
    revokeAllSessions: t.procedure.input(z.any()).mutation(() => null),
  }),
  addressBook: t.router({
    getAddresses: t.procedure.input(z.any().optional()).query(() => null),
    getAddressById: t.procedure.input(z.any()).query(() => null),
    createAddress: t.procedure.input(z.any()).mutation(() => null),
    updateAddress: t.procedure.input(z.any()).mutation(() => null),
    deleteAddress: t.procedure.input(z.any()).mutation(() => null),
    setDefaultAddress: t.procedure.input(z.any()).mutation(() => null),
    getDefaultAddress: t.procedure.input(z.any().optional()).query(() => null),
    getCountries: t.procedure.input(z.any().optional()).query(() => null),
    getAdministrativeDivisions: t.procedure.input(z.any()).query(() => null),
    getAdministrativeDivisionsByParentId: t.procedure.input(z.any()).query(() => null),
  }),
  clientCategories: t.router({
    getCategories: t.procedure.input(z.any().optional()).query(() => null),
    getCategoryById: t.procedure.input(z.any().optional()).query(() => null),
    getCategoryTree: t.procedure.input(z.any().optional()).query(() => null),
    getCategoryBySlug: t.procedure.input(z.any().optional()).query(() => null),
    getRootCategories: t.procedure.input(z.any().optional()).query(() => null),
  }),
  clientNews: t.router({
    getNews: t.procedure.input(z.any().optional()).query(() => null),
    getNewsBySlug: t.procedure.input(z.any().optional()).query(() => null),
    getNewsCategories: t.procedure.input(z.any().optional()).query(() => null),
  }),
  clientProducts: t.router({
    getProducts: t.procedure.input(z.any()).query(() => null),
    getProductById: t.procedure.input(z.any()).query(() => null),
    getProductBySlug: t.procedure.input(z.any()).query(() => null),
    getNewProducts: t.procedure.input(z.any().optional()).query(() => null),
    getFeaturedProducts: t.procedure.input(z.any().optional()).query(() => null),
    getProductsByIds: t.procedure.input(z.any().optional()).query(() => null),
    getProductsByCategory: t.procedure.input(z.any()).query(() => null),
    getProductFilters: t.procedure.input(z.any().optional()).query(() => null),
  }),
  seo: t.router({
    getByPath: t.procedure.input(z.any()).query(() => null),
  }),
  settings: t.router({
    getPublicSettings: t.procedure.input(z.any().optional()).query(() => null),
    getPublicSetting: t.procedure.input(z.any().optional()).query(() => null),
  }),
  clientUser: t.router({
    register: t.procedure.input(z.any()).mutation(() => null),
    login: t.procedure.input(z.any()).mutation(() => null),
    getProfile: t.procedure.input(z.any().optional()).query(() => null),
    updateProfile: t.procedure.input(z.any()).mutation(() => null),
    updateAvatar: t.procedure.input(z.any()).mutation(() => null),
    refreshToken: t.procedure.input(z.any()).mutation(() => null),
    getLoyaltyBalance: t.procedure.input(z.any().optional()).query(() => null),
    getLoyaltyHistory: t.procedure.input(z.any().optional()).query(() => null),
    redeemLoyaltyPoints: t.procedure.input(z.any()).mutation(() => null),
  }),
  sections: t.router({
    list: t.procedure.input(z.any()).query(() => null),
    listAll: t.procedure.input(z.any().optional()).query(() => null),
    create: t.procedure.input(z.any()).mutation(() => null),
    update: t.procedure.input(z.any()).mutation(() => null),
    delete: t.procedure.input(z.any()).mutation(() => null),
    reorder: t.procedure.input(z.any()).mutation(() => null),
  }),
  publicSupportClients: t.router({
    getAvailable: t.procedure.input(z.any().optional()).query(() => null),
    getWidgetScripts: t.procedure.input(z.any().optional()).query(() => null),
    getDefault: t.procedure.input(z.any().optional()).query(() => null),
    getTypes: t.procedure.input(z.any().optional()).query(() => null),
    getByType: t.procedure.input(z.any().optional()).query(() => null),
    testAvailability: t.procedure.input(z.any().optional()).query(() => null),
  }),
  translation: t.router({
    getLocaleConfig: t.procedure.input(z.any().optional()).query(() => null),
    getTranslations: t.procedure.input(z.any().optional()).query(() => null),
    getTranslation: t.procedure.input(z.any().optional()).query(() => null),
    createTranslation: t.procedure.input(z.any()).mutation(() => null),
    updateTranslation: t.procedure.input(z.any()).mutation(() => null),
    deleteTranslation: t.procedure.input(z.any()).mutation(() => null),
    clearCache: t.procedure.input(z.any()).mutation(() => null),
  }),
});

// Export the proper tRPC router type
export type AppRouter = typeof appRouter;
