// AppRouter types for tRPC client
// This file is auto-generated from actual nestjs-trpc routers
// Run 'npm run sync:trpc-types' to regenerate this file
// Generated on: 2025-09-13T06:27:20.304Z

import { initTRPC } from '@trpc/server';
import { z } from 'zod';

// Initialize tRPC for type creation
const t = initTRPC.create();

// Define the AppRouter using tRPC's router structure
// This matches the actual @Router aliases and procedures from nestjs-trpc routers
const appRouter = t.router({
  adminChartData: t.router({
    getChartData: t.procedure.query(() => null),
    getAvailableChartTypes: t.procedure.query(() => null),
  }),
  adminEmailChannel: t.router({
    createChannel: t.procedure.input(z.any()).mutation(() => null),
    getChannels: t.procedure.query(() => null),
    getChannelById: t.procedure.query(() => null),
    getActiveChannels: t.procedure.query(() => null),
    getChannelsByUsageType: t.procedure.query(() => null),
    getDefaultChannel: t.procedure.query(() => null),
    updateChannel: t.procedure.input(z.any()).mutation(() => null),
    deleteChannel: t.procedure.input(z.any()).mutation(() => null),
    setAsDefault: t.procedure.input(z.any()).mutation(() => null),
    testChannel: t.procedure.input(z.any()).mutation(() => null),
    cloneChannel: t.procedure.input(z.any()).mutation(() => null),
  }),
  adminFirebaseConfig: t.router({
    getAllConfigs: t.procedure.query(() => null),
    getConfig: t.procedure.query(() => null),
    createConfig: t.procedure.input(z.any()).mutation(() => null),
    updateConfig: t.procedure.input(z.any()).mutation(() => null),
    deleteConfig: t.procedure.input(z.any()).mutation(() => null),
  }),
  adminLanguage: t.router({
    getLanguages: t.procedure.query(() => null),
    getActiveLanguages: t.procedure.query(() => null),
    getLanguageById: t.procedure.query(() => null),
    getDefaultLanguage: t.procedure.query(() => null),
    createLanguage: t.procedure.input(z.any()).mutation(() => null),
    updateLanguage: t.procedure.input(z.any()).mutation(() => null),
    deleteLanguage: t.procedure.input(z.any()).mutation(() => null),
    setDefaultLanguage: t.procedure.input(z.any()).mutation(() => null),
    toggleLanguageStatus: t.procedure.input(z.any()).mutation(() => null),
    updateSortOrders: t.procedure.input(z.any()).mutation(() => null),
  }),
  adminMailTemplate: t.router({
    createTemplate: t.procedure.input(z.any()).mutation(() => null),
    getTemplates: t.procedure.query(() => null),
    getTemplateById: t.procedure.query(() => null),
    getTemplateByName: t.procedure.query(() => null),
    updateTemplate: t.procedure.input(z.any()).mutation(() => null),
    deleteTemplate: t.procedure.input(z.any()).mutation(() => null),
    processTemplate: t.procedure.input(z.any()).mutation(() => null),
    cloneTemplate: t.procedure.input(z.any()).mutation(() => null),
    getTemplateTypes: t.procedure.query(() => null),
    getStatistics: t.procedure.query(() => null),
    bulkUpdateStatus: t.procedure.input(z.any()).mutation(() => null),
    searchTemplates: t.procedure.query(() => null),
  }),
  adminPostCategories: t.router({
    getCategories: t.procedure.query(() => null),
    getCategoryById: t.procedure.query(() => null),
    createCategory: t.procedure.input(z.any()).mutation(() => null),
    updateCategory: t.procedure.input(z.any()).mutation(() => null),
    deleteCategory: t.procedure.input(z.any()).mutation(() => null),
  }),
  adminPostTags: t.router({
    getTags: t.procedure.query(() => null),
    searchTags: t.procedure.query(() => null),
    getTagById: t.procedure.query(() => null),
    createTag: t.procedure.input(z.any()).mutation(() => null),
    updateTag: t.procedure.input(z.any()).mutation(() => null),
    deleteTag: t.procedure.input(z.any()).mutation(() => null),
    getPopularTags: t.procedure.query(() => null),
  }),
  adminPosts: t.router({
    getPosts: t.procedure.query(() => null),
    getPostById: t.procedure.query(() => null),
  }),
  adminProductAttributes: t.router({
    getAll: t.procedure.query(() => null),
    getById: t.procedure.input(z.any()).query(() => null),
    getSelectAttributes: t.procedure.query(() => null),
    getFilterableAttributes: t.procedure.query(() => null),
    create: t.procedure.input(z.any()).mutation(() => null),
    update: t.procedure.input(z.any()).mutation(() => null),
    delete: t.procedure.input(z.any()).mutation(() => null),
    getAttributeValues: t.procedure.query(() => null),
    createAttributeValue: t.procedure.input(z.any()).mutation(() => null),
    updateAttributeValue: t.procedure.input(z.any()).mutation(() => null),
    deleteAttributeValue: t.procedure.input(z.any()).mutation(() => null),
    getStats: t.procedure.query(() => null),
    getAttributeTranslations: t.procedure.input(z.any()).query(() => null),
    getByIdWithTranslations: t.procedure.input(z.any()).query(() => null),
    createAttributeTranslation: t.procedure.input(z.any()).mutation(() => null),
    updateAttributeTranslation: t.procedure.input(z.any()).mutation(() => null),
    deleteAttributeTranslation: t.procedure.input(z.any()).mutation(() => null),
  }),
  adminProductBrands: t.router({
    getAll: t.procedure.query(() => null),
    getById: t.procedure.input(z.any()).query(() => null),
    create: t.procedure.input(z.any()).mutation(() => null),
    update: t.procedure.input(z.any()).mutation(() => null),
    delete: t.procedure.input(z.any()).mutation(() => null),
    getStats: t.procedure.query(() => null),
    getBrandTranslations: t.procedure.input(z.any()).query(() => null),
    getByIdWithTranslations: t.procedure.input(z.any()).query(() => null),
    createBrandTranslation: t.procedure.input(z.any()).mutation(() => null),
    updateBrandTranslation: t.procedure.input(z.any()).mutation(() => null),
    deleteBrandTranslation: t.procedure.input(z.any()).mutation(() => null),
  }),
  adminProductCategories: t.router({
    getAll: t.procedure.query(() => null),
    getTree: t.procedure.query(() => null),
    getRootCategories: t.procedure.query(() => null),
    getCategoryChildren: t.procedure.query(() => null),
    getFilteredTree: t.procedure.query(() => null),
    getById: t.procedure.input(z.any()).query(() => null),
    create: t.procedure.input(z.any()).mutation(() => null),
    update: t.procedure.input(z.any()).mutation(() => null),
    delete: t.procedure.input(z.any()).mutation(() => null),
    getStats: t.procedure.query(() => null),
    getCategoryTranslations: t.procedure.input(z.any()).query(() => null),
    getByIdWithTranslations: t.procedure.input(z.any()).query(() => null),
    getTreeWithTranslations: t.procedure.query(() => null),
    createCategoryTranslation: t.procedure.input(z.any()).mutation(() => null),
    updateCategoryTranslation: t.procedure.input(z.any()).mutation(() => null),
    deleteCategoryTranslation: t.procedure.input(z.any()).mutation(() => null),
  }),
  adminProducts: t.router({
    list: t.procedure.input(z.any()).query(() => null),
    detail: t.procedure.input(z.any()).query(() => null),
    create: t.procedure.input(z.any()).mutation(() => null),
    update: t.procedure.input(z.any()).mutation(() => null),
    delete: t.procedure.input(z.any()).mutation(() => null),
    stats: t.procedure.query(() => null),
    updateStatus: t.procedure.input(z.any()).mutation(() => null),
  }),
  clientProducts: t.router({
    list: t.procedure.input(z.any()).query(() => null),
    detail: t.procedure.input(z.any()).query(() => null),
    featured: t.procedure.query(() => null),
    byCategory: t.procedure.query(() => null),
    byBrand: t.procedure.query(() => null),
  }),
  publicProducts: t.router({
    list: t.procedure.input(z.any()).query(() => null),
    detail: t.procedure.input(z.any()).query(() => null),
    featured: t.procedure.query(() => null),
    byCategory: t.procedure.query(() => null),
    byBrand: t.procedure.query(() => null),
    search: t.procedure.query(() => null),
  }),
  'admin.seo': t.router({
    getAll: t.procedure.query(() => null),
    getByPath: t.procedure.query(() => null),
    create: t.procedure.input(z.any()).mutation(() => null),
    update: t.procedure.input(z.any()).mutation(() => null),
    delete: t.procedure.input(z.any()).mutation(() => null),
  }),
  'admin.settings': t.router({
    getAll: t.procedure.query(() => null),
    getById: t.procedure.input(z.any()).query(() => null),
    getByKey: t.procedure.query(() => null),
    getByGroup: t.procedure.query(() => null),
    create: t.procedure.input(z.any()).mutation(() => null),
    update: t.procedure.input(z.any()).mutation(() => null),
    bulkUpdate: t.procedure.input(z.any()).mutation(() => null),
    delete: t.procedure.input(z.any()).mutation(() => null),
  }),
  adminMedia: t.router({
    getUserMedia: t.procedure.query(() => null),
    getMediaById: t.procedure.query(() => null),
    updateMedia: t.procedure.input(z.any()).mutation(() => null),
    deleteMedia: t.procedure.input(z.any()).mutation(() => null),
    deleteMultipleMedia: t.procedure.input(z.any()).mutation(() => null),
    getMediaStats: t.procedure.query(() => null),
    getRecentMedia: t.procedure.query(() => null),
  }),
  adminStorage: t.router({
    getStorageConfig: t.procedure.query(() => null),
    updateStorageConfig: t.procedure.input(z.any()).mutation(() => null),
    testStorageConnection: t.procedure.input(z.any()).mutation(() => null),
  }),
  adminPermission: t.router({
    createPermission: t.procedure.input(z.any()).mutation(() => null),
    getAllPermissions: t.procedure.query(() => null),
    getPermissionById: t.procedure.query(() => null),
    updatePermission: t.procedure.input(z.any()).mutation(() => null),
    deletePermission: t.procedure.input(z.any()).mutation(() => null),
    assignPermissionToRole: t.procedure.input(z.any()).mutation(() => null),
    removePermissionFromRole: t.procedure.input(z.any()).mutation(() => null),
    getRolePermissions: t.procedure.query(() => null),
    grantPermissions: t.procedure.input(z.any()).mutation(() => null),
    checkPermission: t.procedure.query(() => null),
  }),
  adminRole: t.router({
    getAllRoles: t.procedure.query(() => null),
    getRoleById: t.procedure.query(() => null),
    createRole: t.procedure.input(z.any()).mutation(() => null),
    updateRole: t.procedure.input(z.any()).mutation(() => null),
    deleteRole: t.procedure.input(z.any()).mutation(() => null),
    getAvailablePermissions: t.procedure.query(() => null),
    getRoleStatistics: t.procedure.query(() => null),
    toggleRoleStatus: t.procedure.input(z.any()).mutation(() => null),
    duplicateRole: t.procedure.input(z.any()).mutation(() => null),
    addPermissionsToRole: t.procedure.input(z.any()).mutation(() => null),
    searchUsersForRole: t.procedure.query(() => null),
    addUsersToRole: t.procedure.input(z.any()).mutation(() => null),
  }),
  adminUserActivity: t.router({
    getUserActivityStatus: t.procedure.query(() => null),
    getBulkUserActivityStatus: t.procedure.query(() => null),
    getCurrentlyActiveUsers: t.procedure.query(() => null),
    getRecentlyActiveUsers: t.procedure.query(() => null),
    getActivitySummary: t.procedure.query(() => null),
  }),
  adminUserStatistics: t.router({
    getUserStatistics: t.procedure.query(() => null),
  }),
  adminUser: t.router({
    createUser: t.procedure.input(z.any()).mutation(() => null),
    getAllUsers: t.procedure.query(() => null),
    getUserById: t.procedure.query(() => null),
    updateUser: t.procedure.input(z.any()).mutation(() => null),
    deleteUser: t.procedure.input(z.any()).mutation(() => null),
    updateUserStatus: t.procedure.input(z.any()).mutation(() => null),
    updateUserProfileById: t.procedure.input(z.any()).mutation(() => null),
    getProfile: t.procedure.query(() => null),
    updateProfile: t.procedure.input(z.any()).mutation(() => null),
    updatePassword: t.procedure.input(z.any()).mutation(() => null),
  }),
});

// Export the proper tRPC router type
export type AppRouter = typeof appRouter;
